/** Ordem aproximada respeitando FKs ao importar dados */
export const TABLE_EXPORT_ORDER = [
  'services',
  'system_settings',
  'employees',
  'clients',
  'profiles',
  'employee_permissions',
  'employee_client_assignments',
  'client_services',
  'department_tasks',
  'chat_messages',
  'client_meetings',
  'whatsapp_messages',
  'whatsapp_approvals',
  'workflow_history',
  'client_approvals',
  'commercial_whatsapp_configs',
  'commercial_leads',
  'crm_pipelines',
  'crm_pipeline_columns',
  'crm_leads',
  'crm_lead_messages',
  'crm_whatsapp_sessions',
  'social_contents',
  'social_copies',
  'notifications',
  'push_subscriptions',
  'employee_integrations',
  'google_events',
  'agency_integrations',
  'ads_connections',
  'programacao_afazer',
  'programacao_finalizadas',
];

/** SQL do repositório — rodar no destino DEPOIS do schema base */
export const REPO_SQL_ORDER = [
  'supabase_workflow_migration.sql',
  'supabase_crm_migration.sql',
  'add_parent_id_migration.sql',
  'google_calendar_setup.sql',
  'google_calendar_colors.sql',
  'google_calendar_global_rls.sql',
  'fix_calendar.sql',
  'supabase/social_media_tables.sql',
  'supabase/ads_integration_setup.sql',
  'supabase/push_subscriptions_migration.sql',
  'supabase/create_notifications_table.sql',
  'supabase/apply_orphan_triggers.sql',
  'supabase/fix_social_rls.sql',
];
